// Generated by gencpp from file assignment_1/GoToResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_1_MESSAGE_GOTORESPONSE_H
#define ASSIGNMENT_1_MESSAGE_GOTORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_1
{
template <class ContainerAllocator>
struct GoToResponse_
{
  typedef GoToResponse_<ContainerAllocator> Type;

  GoToResponse_()
    : o(0)  {
    }
  GoToResponse_(const ContainerAllocator& _alloc)
    : o(0)  {
  (void)_alloc;
    }



   typedef int64_t _o_type;
  _o_type o;





  typedef boost::shared_ptr< ::assignment_1::GoToResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_1::GoToResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToResponse_

typedef ::assignment_1::GoToResponse_<std::allocator<void> > GoToResponse;

typedef boost::shared_ptr< ::assignment_1::GoToResponse > GoToResponsePtr;
typedef boost::shared_ptr< ::assignment_1::GoToResponse const> GoToResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_1::GoToResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_1::GoToResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'assignment_1': ['/home/andrea/experimental_robotics_lab/src/assignment_1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::GoToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::GoToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::GoToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::GoToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::GoToResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::GoToResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_1::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0744378b98a80c5b1fe9704c7ae11cdf";
  }

  static const char* value(const ::assignment_1::GoToResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0744378b98a80c5bULL;
  static const uint64_t static_value2 = 0x1fe9704c7ae11cdfULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_1::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_1/GoToResponse";
  }

  static const char* value(const ::assignment_1::GoToResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_1::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 o\n\
\n\
";
  }

  static const char* value(const ::assignment_1::GoToResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_1::GoToResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.o);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_1::GoToResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_1::GoToResponse_<ContainerAllocator>& v)
  {
    s << indent << "o: ";
    Printer<int64_t>::stream(s, indent + "  ", v.o);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_1_MESSAGE_GOTORESPONSE_H
